### ISSUE TITLE
Current cleaning script does not work with jsons from Custom Clean UI.

### ISSUE THREAD

**Issue by kathy-snider** [DCAN-Labs/CustomClean#2]
We have changed the format of the json files to, eventually, allow the user to edit an existing json from the GUI without the original directory being around anymore. Also to allow more features in the cleaning script (like patterns, etc.) But we have not re-written the GUI, so the current GUI makes one format of json and the cleaning script takes a different format. Bottom line, the GUI is kind of not used right now.

**Comment by LuciMoore** [comment]
GUI no longer being maintained - README is now updated
