### ISSUE TITLE
Need documentation about design decisions.

### ISSUE THREAD

**Issue by kathy-snider** [DCAN-Labs/CustomClean#3]
For example: what if a "folder" is listed in the json with "delete", but not all of its children are deleted (e.g. more files are written now than when the json was created, so removing the ones listed for "delete" in the json leaves some other stuff around. Should we delete the folder anyway? What if a folder is empty but it's status is "keep"? Should we delete it anyway? 
We need to remember what was decided or to decide anew. Either way, we need to document so both the developer and the user know what the code is _supposed_ to do.

**Comment by audreymhoughton** [comment]
@madisoth stated this was covered in the two commits after this issue was posted.

https://github.com/DCAN-Labs/CustomClean/commit/98732f71df9c4cab6575838ea94488486b1b17b0

https://github.com/DCAN-Labs/CustomClean/commit/6cb1fdfcf3758d96316afc86abc5b801ff6a2282
