### ISSUE TITLE
Changed File Names in pipeline

### ISSUE THREAD

**Issue by Noah-Baden** [DCAN-Labs/CustomClean#8]
Hi, I'm Noah Baden, with the Wash U team downloading the ABCD Year 2 Data, and going through the given data, it showed that the CustomClean script stopped working because the names of all the files were changed from task-**** to ses-2YearFollowUpYArm1_task-****. So you may need to re-run the script with an edited json to fix this issue.

**Comment by ericearl** [comment]
@Noah-Baden This isn't an issue with the CustomClean software, but an issue with the ABCD Study BIDS data collection 3165.

I'm no longer a part of DCAN Labs, so I would recommend you submit this issue or something like it to:

https://github.com/ABCD-STUDY/nda-abcd-collection-3165

They watch those issues more closely too, FWIW. Good luck!

**Comment by audreymhoughton** [comment]
Being discussed here: https://github.com/ABCD-STUDY/nda-abcd-collection-3165/issues/65
